from __future__ import annotations
from typing import List
from . import astnodes as A
import textwrap

HEADER = ("# Auto-generated by FlightLang PoC\n""from flightlang.runtime import Runtime, WaypointGrid\n\n""rt = Runtime()\n")

def py_val(expr):
    if isinstance(expr, dict):
        k = expr.get("kind")
        if k == "number":
            v = expr["value"]; unit = expr.get("unit")
            return repr({"value": v, "unit": unit})
        if k == "string":
            return repr(expr["value"])
        if k == "ident":
            return f"env.get({repr(expr['name'])}, {repr({'value': None, 'unit': None})})"
        if k == "call":
            name = expr["name"]
            kwargs = {k: py_val(v) for k, v in expr["kwargs"].items()}
            if name == "waypoint_grid":
                return f"WaypointGrid(spacing={kwargs.get('spacing')}, bearing={kwargs.get('bearing')})"
            return repr({"call": name, "kwargs": expr["kwargs"]})
    return repr(expr)

def generate(prog: A.Program) -> str:
    parts: List[str] = [HEADER]
    parts.append("env = {}\n")
    for let in prog.lets:
        parts.append(f"env[{let.name!r}] = {{'value': {let.value_num}, 'unit': {let.value_unit!r}}}\n")
    ms = prog.mission
    pre = repr(ms.preflight.condition) if ms.preflight else 'None'
    geo = repr(ms.geofence.polygon_name) if ms.geofence else 'None'
    parts.append(f"rt.set_metadata(name={ms.name!r}, preflight={pre}, geofence={geo})\n")

    parts.append("states = {}\n")
    for st in ms.states:
        parts.append(f"states[{st.name!r}] = []\n")
        for item in st.items:
            if isinstance(item, A.Transition):
                parts.append(f"states[{st.name!r}].append(('transition', {item.event!r}, {item.target_state!r}))\n")
            elif isinstance(item, A.Action):
                at_speed = py_val(item.at_speed) if item.at_speed is not None else "None"
                args_py = ", ".join(py_val(a) for a in item.args)
                parts.append(f"states[{st.name!r}].append(('action', {item.name!r}, [{args_py}], {at_speed}, {item.then_resume}))\n")
            elif isinstance(item, A.Deadline):
                parts.append(f"states[{st.name!r}].append(('deadline', {item.ms}))\n")

    parts.append("rt.load_states(states)\n")
    start_state = prog.mission.states[0].name if prog.mission.states else 'Idle'
    parts.append(f"rt.set_start_state({start_state!r})\n")

    parts.append(textwrap.dedent('\nif __name__ == "__main__":\n        schedule = [\n            (0, "arm"),\n            (1000, "reached_altitude"),\n            (3000, "obstacle_detected"),\n            (5000, "clear"),\n            (7000, "grid_complete"),\n            (9000, "landed"),\n        ]\n        rt.run(schedule)\n'))
    return ''.join(parts)
